### ISSUE TITLE
Unsupported feed

### ISSUE THREAD

**Issue by SandroLuck** [changun/CollMetric#4]
Hi Changun, 

I've been trying to start this project for a few days now. 
But I'm running into the same error over and over again : Unsupported feed type. 
I've tried it both with tensorflow GPU and CPU and on two different tf versions. 
I'm using Windows and Python 3.5.2  and have numpy and all other dependecies named installed.

Every hit you could give me would be extremely appreciated.

```
10403 features over tag_occurence_thres (5)
Split data into train/valid/test: 100%|################################################| 7947/7947 [00:03<00:00, 2202.89it/s]
79527/25186/31555 train/valid/test samples
2017-07-30 13:19:08.928815: W C:\tf_jenkins\home\workspace\nightly-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_gu
ard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Recall on (sampled) validation set: 0.0
Optimizing...:   0%|                                                                                 | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 13
27, in _do_call
    return fn(*args)
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 13
06, in _run_fn
    status, run_metadata)
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py",
line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\CML.py", line 397, in <module>
    optimize(model, sampler, train, valid)
  File ".\CML.py", line 361, in optimize
    model.negative_samples: neg})
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 89
5, in run
    run_metadata_ptr)
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 11
24, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 13
21, in _do_run
    options, run_metadata)
  File "C:\Users\Sandro\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 13
40, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type
```

**Comment by changun** [comment]
Hi Sandro,

It seems to be caused by this switch statement in tensorflow:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/tf_session_helper.cc#L129

I don't see this issue on Linux machines and do not have a Windows machine at hand to reproduce it. I would try print the type of the numpy arrays that are being fed into the tensorflow 
e.g.
```
print(user_pos.dtype, neg.dtype) 
```
and see if they are one of the types supported by Tensorflow (according to that switch statement). If not so, you can try to convert them to int32 by:
```
user_pos = numpy.asarray(user_pos.dtype, dtype="int32")
```

Let me know how it goes. Thanks!

**Comment by SandroLuck** [comment]
Thank you for your help.
Due to additional erros popping up, I won't pursue developig this on a Windows machine and will switch to a Linux implementation. Thank you for your effort.

**Comment by changun** [comment]
Got it! Feel free to let me know if you see any other issues with the code. Thanks!
